// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGWitsnfH_qQqGkUNVc5iJ1Kny0lstzqM',
    appId: '1:382701753480:web:1c30ebba346984c9cffb3d',
    messagingSenderId: '382701753480',
    projectId: 'alhorra-0',
    authDomain: 'alhorra-0.firebaseapp.com',
    storageBucket: 'alhorra-0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEKkUOuFB5snloK8tyYJLaX7kKE60ivn8',
    appId: '1:382701753480:android:7e388378a1a556d7cffb3d',
    messagingSenderId: '382701753480',
    projectId: 'alhorra-0',
    storageBucket: 'alhorra-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwn6hh_fPQY7CMKCoKkOmL6OzaBVa2RBE',
    appId: '1:382701753480:ios:f9f1915b2e943e7bcffb3d',
    messagingSenderId: '382701753480',
    projectId: 'alhorra-0',
    storageBucket: 'alhorra-0.appspot.com',
    iosBundleId: 'com.example.alhoraProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwn6hh_fPQY7CMKCoKkOmL6OzaBVa2RBE',
    appId: '1:382701753480:ios:f9f1915b2e943e7bcffb3d',
    messagingSenderId: '382701753480',
    projectId: 'alhorra-0',
    storageBucket: 'alhorra-0.appspot.com',
    iosBundleId: 'com.example.alhoraProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGWitsnfH_qQqGkUNVc5iJ1Kny0lstzqM',
    appId: '1:382701753480:web:705aaebf5f40ca9acffb3d',
    messagingSenderId: '382701753480',
    projectId: 'alhorra-0',
    authDomain: 'alhorra-0.firebaseapp.com',
    storageBucket: 'alhorra-0.appspot.com',
  );
}
